Meteor.subscribe("courses");
Meteor.subscribe("rooms");
Meteor.subscribe("teachers");
Meteor.subscribe("students");
Meteor.subscribe("classes");
Meteor.subscribe("schedules");
Meteor.subscribe("rows");
Meteor.subscribe("columns");
Meteor.subscribe("options");
